FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV HOSTNAME="0.0.0.0"

COPY public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY .next/standalone ./
COPY .next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
